events {
    worker_connections 1024;  # Set the max number of connections per worker
}

http {
    # HTTP context: This is where you define your server blocks
    server {
        listen 8080;  # Nginx will listen on port 80 (inside the container)

        # Define a location block to handle the root URL (frontend)
        location / {
            # Proxy requests to the backend (netflix-frontend) on port 3000
            proxy_pass http://netflix-frontend:3000;  # Ensure the backend service is available
            proxy_set_header Host $host;  # Set the Host header to the incoming request's host
            proxy_set_header X-Real-IP $remote_addr;  # Forward the real client IP address
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # Preserve the client’s original IP
            proxy_set_header X-Forwarded-Proto $scheme;  # Preserve the original protocol (HTTP/HTTPS)
        }

        # Optional: Define another location block to handle requests to '/api' for the catalog service
    }
}
#