name: Netflix stack deploy

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: "Target service to deploy"
        required: true
        type: string
      image:
        description: "New Docker image version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  UpdateComposeYaml:
    runs-on: ubuntu-latest
    outputs:
      service_name: ${{ github.event.inputs.service_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update docker-compose.yml
        run: |
          yq e ".services.${{ github.event.inputs.service_name }}.image = \"${{ github.event.inputs.image }}\"" -i docker-compose.yml

      - name: Check for changes
        id: git_check
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "::set-output name=has_changes::false"
          else
            echo "::set-output name=has_changes::true"
          fi

      - name: Commit and push changes
        if: steps.git_check.outputs.has_changes == 'true'
        run: |
          git config --local user.email "guymeltzer28@gmail.com"
          git config --local user.name "guymeltzer"

          git add docker-compose.yml
          git commit -m "Update ${{ github.event.inputs.service_name }} image to ${{ github.event.inputs.image }}"
          git push origin main
  Deploy:
    name: Deploy a Netflix stack service
    needs: UpdateComposeYaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Get EC2 public IP
        id: get_ec2_ip
        run: |
          EC2_PUBLIC_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=guy-netflix-infra-tfstate-*" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
          echo "EC2_PUBLIC_IP=${EC2_PUBLIC_IP}" >> $GITHUB_OUTPUT

      - name: Debug AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}"

      - name: Update the Docker Compose project in the EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.get_ec2_ip.outputs.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            repo_dir=NetflixMovieCatalog_${GITHUB_RUN_ID}
            rm -rf $repo_dir
            
            # Clone the full repository URL
            git clone https://github.com/${{ github.repository }}.git $repo_dir
            cd $repo_dir
            
            # Set the correct service name for Docker Compose
            service_name=${{ needs.UpdateComposeYaml.outputs.service_name }}
            
            # Ensure AWS credentials are available when running Docker Compose
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
            
            docker rm -v -f $(docker ps -qa)
            # Run the Docker Compose service
            docker compose up -d $service_name
            
            echo "Deploy completed."