name: Netflix stack deploy

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: "Target service to deploy"
        required: true
        type: string
      image:
        description: "New Docker image version"
        required: true
        type: string

permissions:
  contents: write

jobs:
  UpdateComposeYaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update docker-compose.yml
        run: |
         yq e ".services.${{ github.event.inputs.service_name }}.image = \"${{ github.event.inputs.image }}\"" -i docker-compose.yml


      - name: Commit and push changes
        run: |
          git config --local user.email "guymeltzer28@gmail.com"
          git config --local user.name "guymeltzer"

          git add docker-compose.yml
          git commit -m "Update ${{ github.event.inputs.service_name }} image to ${{ github.event.inputs.image }}"
          git push origin main
##
  Deploy:
    name: Deploy a Netflix stack service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Update the Docker Compose project in the EC2
        env:
          EC2_PUBLIC_IP: "13.49.46.107"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            repo_dir=NetflixMovieCatalog_${GITHUB_RUN_ID}
            # Clone the full repository URL
            git clone https://github.com/${{ github.repository }}.git $repo_dir
            cd $repo_dir

            # Set the correct service name for Docker Compose
            service_name=netflix-catalog

            # Run the Docker Compose service
            docker-compose up -d $service_name

            echo "Deploy completed."
  
  
