name: Deploy Nginx and App

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 51.20.79.83
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Nginx Configuration
        run: |
          echo "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 400 mykey.pem
          scp -o StrictHostKeyChecking=no -i mykey.pem nginx-config/default.conf ubuntu@51.20.79.83:/etc/nginx/conf.d/default.conf

      - name: Restart Nginx
        run: |
          ssh -i mykey.pem ubuntu@51.20.79.83 'sudo systemctl restart nginx'
          
