name: Deploy Nginx Configuration

on:
  push:
    branches:
      - main
env:
  EC2_PUBLIC_IP: 13.60.254.26
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: SSH to EC2 instance
      run: |
          echo "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 400 mykey.pem
          cat mykey.pem

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Transfer Nginx Config Files
      run: |
        scp -i mykey.pem -o StrictHostKeyChecking=no nginx-config/default.conf ubuntu@$EC2_PUBLIC_IP:/home/ubuntu
        ssh -i mykey.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP 'sudo mv /home/ubuntu/default.conf /etc/nginx/conf.d/default.conf'
    - name: Restart Nginx Service
      run: |
        ssh -i mykey.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP 'sudo systemctl restart nginx'
    - name: Check Nginx Status (on failure)
      if: failure()
      run: |
          ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@$EC2_PUBLIC_IP 'sudo systemctl status nginx.service'
          ssh -o StrictHostKeyChecking=no -i mykey.pem ubuntu@$EC2_PUBLIC_IP 'sudo journalctl -xeu nginx.service'